In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("salary.csv")
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [11]:
print(df.to_string())

      Age  Gender Education Level                              Job Title  Years of Experience    Salary
0    32.0    Male      Bachelor's                      Software Engineer                  5.0   90000.0
1    28.0  Female        Master's                           Data Analyst                  3.0   65000.0
2    45.0    Male             PhD                         Senior Manager                 15.0  150000.0
3    36.0  Female      Bachelor's                        Sales Associate                  7.0   60000.0
4    52.0    Male        Master's                               Director                 20.0  200000.0
5    29.0    Male      Bachelor's                      Marketing Analyst                  2.0   55000.0
6    42.0  Female        Master's                        Product Manager                 12.0  120000.0
7    31.0    Male      Bachelor's                          Sales Manager                  4.0   80000.0
8    26.0  Female      Bachelor's                  Marketing Coordinator                  1.0   45000.0
9    38.0    Male             PhD                       Senior Scientist                 10.0  110000.0
10   29.0    Male        Master's                     Software Developer                  3.0   75000.0
11   48.0  Female      Bachelor's                             HR Manager                 18.0  140000.0
12   35.0    Male      Bachelor's                      Financial Analyst                  6.0   65000.0
13   40.0  Female        Master's                        Project Manager                 14.0  130000.0
14   27.0    Male      Bachelor's                   Customer Service Rep                  2.0   40000.0
15   44.0    Male      Bachelor's                     Operations Manager                 16.0  125000.0
16   33.0  Female        Master's                      Marketing Manager                  7.0   90000.0
17   39.0    Male             PhD                        Senior Engineer                 12.0  115000.0
18   25.0  Female      Bachelor's                       Data Entry Clerk                  0.0   35000.0
19   51.0    Male      Bachelor's                         Sales Director                 22.0  180000.0
20   34.0  Female        Master's                       Business Analyst                  5.0   80000.0
21   47.0    Male        Master's                       VP of Operations                 19.0  190000.0
22   30.0    Male      Bachelor's                             IT Support                  2.0   50000.0
23   36.0  Female      Bachelor's                              Recruiter                  9.0   60000.0
24   41.0    Male        Master's                      Financial Manager                 13.0  140000.0
25   28.0  Female      Bachelor's                Social Media Specialist                  3.0   45000.0
26   37.0  Female        Master's                       Software Manager                 11.0  110000.0
27   24.0    Male      Bachelor's                       Junior Developer                  1.0   40000.0
28   43.0  Female             PhD                      Senior Consultant                 15.0  140000.0
29   33.0    Male        Master's                       Product Designer                  6.0   90000.0
30   50.0    Male      Bachelor's                                    CEO                 25.0  250000.0
31   31.0  Female      Bachelor's                             Accountant                  4.0   55000.0
32   29.0    Male        Master's                         Data Scientist                  3.0   75000.0
33   39.0  Female      Bachelor's                   Marketing Specialist                 10.0   65000.0
34   46.0    Male             PhD                         Senior Manager                 20.0  170000.0
35   27.0    Male      Bachelor's                       Technical Writer                  2.0   45000.0
36   35.0  Female      Bachelor's                          HR Generalist                  7.0   60000.0
37   42.0    Male        Master's                       Project Engineer                 14.0  115000.0
38   26.0  Female      Bachelor's                   Customer Success Rep                  1.0   40000.0
39   49.0    Male      Bachelor's                        Sales Executive                 21.0  160000.0
40   34.0  Female        Master's                            UX Designer                  5.0   80000.0
41   48.0    Male        Master's                    Operations Director                 18.0  190000.0
42   30.0    Male      Bachelor's                       Network Engineer                  3.0   60000.0
43   36.0  Female      Bachelor's               Administrative Assistant                  8.0   45000.0
44   41.0    Male        Master's                    Strategy Consultant                 13.0  130000.0
45   28.0  Female      Bachelor's                             Copywriter                  2.0   40000.0
46   32.0    Male      Bachelor's                        Account Manager                  5.0   75000.0
47   45.0  Female        Master's                  Director of Marketing                 16.0  180000.0
48   38.0    Male             PhD                       Senior Scientist                 11.0  120000.0
49   25.0    Male      Bachelor's                      Help Desk Analyst                  0.0   35000.0
50   51.0  Female      Bachelor's               Customer Service Manager                 22.0  130000.0
51   33.0    Male        Master's          Business Intelligence Analyst                  7.0   85000.0
52   40.0  Female      Bachelor's                      Event Coordinator                 12.0   60000.0
53   47.0    Male        Master's                          VP of Finance                 19.0  200000.0
54   29.0  Female      Bachelor's                       Graphic Designer                  3.0   50000.0
55   36.0    Male      Bachelor's                          Sales Manager                  9.0   95000.0
56   27.0  Female        Master's                          UX Researcher                  2.0   65000.0
57   43.0    Male             PhD                        Senior Engineer                 17.0  140000.0
58   30.0  Female      Bachelor's                   Social Media Manager                  4.0   55000.0
59   35.0    Male        Master's                        Product Manager                  7.0  105000.0
60   51.0  Female        Master's                 Director of Operations                 23.0  170000.0
61   29.0    Male      Bachelor's                      Marketing Analyst                  3.0   50000.0
62   40.0  Female      Bachelor's                             HR Manager                 12.0   80000.0
63   47.0    Male             PhD                  Senior Data Scientist                 21.0  180000.0
64   26.0    Male      Bachelor's                      Junior Accountant                  1.0   35000.0
65   38.0  Female        Master's              Digital Marketing Manager                 10.0   90000.0
66   46.0    Male      Bachelor's                             IT Manager                 19.0  120000.0
67   31.0  Female      Bachelor's        Customer Service Representative                  5.0   45000.0
68   34.0    Male        Master's           Business Development Manager                  8.0   90000.0
69   49.0  Female        Master's               Senior Financial Analyst                 18.0  150000.0
70   33.0    Male      Bachelor's                          Web Developer                  6.0   65000.0
71   39.0  Female      Bachelor's                              Recruiter                 11.0   70000.0
72   45.0    Male             PhD                      Research Director                 16.0  190000.0
73   28.0    Male      Bachelor's           Technical Support Specialist                  2.0   40000.0
74   42.0  Female        Master's                      Creative Director                 14.0  120000.0
75   37.0    Male      Bachelor's                        Project Manager                 10.0   95000.0
76   50.0  Female      Bachelor's                     Operations Manager                 22.0  160000.0
77   32.0    Male        Master's               Senior Software Engineer                  6.0  100000.0
78   48.0  Female        Master's               Human Resources Director                 20.0  180000.0
79   30.0  Female      Bachelor's              Content Marketing Manager                  3.0   55000.0
80   36.0    Male      Bachelor's                    Technical Recruiter                  8.0   70000.0
81   41.0  Female        Master's                           Data Analyst                 13.0   80000.0
82   25.0    Male      Bachelor's                   Sales Representative                  0.0   30000.0
83   52.0    Male             PhD               Chief Technology Officer                 24.0  250000.0
84   29.0  Female      Bachelor's                        Junior Designer                  2.0   40000.0
85   34.0  Female        Master's                      Financial Advisor                 10.0   95000.0
86   27.0    Male      Bachelor's                 Junior Account Manager                  2.0   45000.0
87   40.0  Female      Bachelor's                          HR Generalist                 15.0   80000.0
88   46.0    Male        Master's                 Senior Project Manager                 21.0  135000.0
89   31.0  Female      Bachelor's                  Marketing Coordinator                  6.0   55000.0
90   36.0    Male             PhD                    Principal Scientist                 11.0  120000.0
91   29.0  Female      Bachelor's                        Sales Associate                  3.0   40000.0
92   43.0    Male      Bachelor's                   Supply Chain Manager                 18.0  105000.0
93   52.0  Female        Master's               Senior Marketing Manager                 25.0  170000.0
94   33.0    Male      Bachelor's                       Business Analyst                  7.0   75000.0
95   39.0  Female      Bachelor's                    Training Specialist                 12.0   65000.0
96   47.0    Male             PhD                     Research Scientist                 22.0  160000.0
97   26.0    Male      Bachelor's              Junior Software Developer                  1.0   35000.0
98   38.0  Female        Master's               Public Relations Manager                 10.0   90000.0
99   45.0    Male      Bachelor's                     Operations Analyst                 20.0  110000.0
100  31.0  Female      Bachelor's                      Event Coordinator                  5.0   45000.0
101  35.0    Male        Master's              Product Marketing Manager                  8.0   95000.0
102  49.0  Female        Master's                      Senior HR Manager                 19.0  150000.0
103  33.0    Male      Bachelor's                   Junior Web Developer                  5.0   50000.0
104  39.0  Female        Master's             Senior Project Coordinator                 13.0   80000.0
105  44.0    Male             PhD                     Chief Data Officer                 16.0  220000.0
106  30.0  Female      Bachelor's               Digital Content Producer                  3.0   50000.0
107  36.0    Male      Bachelor's                  IT Support Specialist                  7.0   60000.0
108  41.0  Female        Master's               Senior Marketing Analyst                 14.0  100000.0
109  28.0    Male      Bachelor's               Customer Success Manager                  2.0   40000.0
110  42.0  Female        Master's                Senior Graphic Designer                 15.0  110000.0
111  37.0    Male      Bachelor's               Software Project Manager                  9.0   95000.0
112  50.0  Female      Bachelor's                   Supply Chain Analyst                 22.0  130000.0
113  32.0    Male        Master's                Senior Business Analyst                  6.0   90000.0
114  23.0  Female      Bachelor's               Junior Marketing Analyst                  0.5   35000.0
115  31.0    Male        Master's               Senior Financial Analyst                  6.0   95000.0
116  40.0  Female      Bachelor's                         Office Manager                 15.0   65000.0
117  48.0    Male             PhD                     Principal Engineer                 20.0  170000.0
118  29.0  Female      Bachelor's                   Junior HR Generalist                  3.0   45000.0
119  35.0    Male        Master's                 Senior Product Manager                 10.0  120000.0
120  42.0  Female      Bachelor's                          Sales Manager                 17.0  100000.0
121  53.0    Male        Master's                  Director of Marketing                 25.0  180000.0
122  33.0  Female      Bachelor's              Junior Operations Analyst                  5.0   50000.0
123  38.0    Male      Bachelor's               Customer Service Manager                 11.0   80000.0
124  44.0  Female             PhD                       Senior Scientist                 16.0  140000.0
125  26.0    Male      Bachelor's                      Junior Accountant                  2.0   40000.0
126  37.0  Female        Master's                   Senior HR Generalist                  9.0   95000.0
127  45.0    Male      Bachelor's               Sales Operations Manager                 18.0  110000.0
128  32.0  Female      Bachelor's                  Marketing Coordinator                  4.0   50000.0
129  34.0    Male        Master's              Senior Software Developer                  8.0  105000.0
130  50.0  Female        Master's                 Director of Operations                 21.0  160000.0
131  29.0    Male      Bachelor's                    Junior Web Designer                  3.0   45000.0
132  40.0  Female        Master's             Senior Training Specialist                 12.0  100000.0
133  47.0    Male             PhD              Senior Research Scientist                 22.0  160000.0
134  27.0    Male      Bachelor's            Junior Sales Representative                  1.0   35000.0
135  39.0  Female      Bachelor's               Administrative Assistant                 10.0   55000.0
136  46.0    Male        Master's                 Senior Project Manager                 19.0  140000.0
137  30.0  Female      Bachelor's               Junior Marketing Manager                  4.0   50000.0
138  36.0    Male      Bachelor's                    Junior Data Analyst                  7.0   60000.0
139  43.0  Female        Master's       Senior Product Marketing Manager                 14.0  120000.0
140  28.0    Male      Bachelor's                Junior Business Analyst                  2.0   40000.0
141  41.0  Female        Master's               Senior Marketing Manager                 13.0  110000.0
142  33.0    Male      Bachelor's              Junior Software Developer                  5.0   50000.0
143  47.0    Male      Bachelor's                   Senior Sales Manager                 20.0  135000.0
144  25.0  Female        Master's            Junior Marketing Specialist                  1.5   40000.0
145  34.0    Male      Bachelor's                Senior Business Analyst                  8.0   90000.0
146  42.0  Female             PhD                  Senior Data Scientist                 16.0  150000.0
147  31.0    Male      Bachelor's                 Junior Project Manager                  4.0   60000.0
148  38.0  Female      Bachelor's                      Senior Accountant                 10.0   80000.0
149  45.0    Male        Master's                      Director of Sales                 19.0  175000.0
150  29.0  Female      Bachelor's                       Junior Recruiter                  3.0   45000.0
151  36.0    Male        Master's    Senior Business Development Manager                 11.0  120000.0
152  43.0  Female             PhD                Senior Product Designer                 18.0  140000.0
153  26.0    Male      Bachelor's     Junior Customer Support Specialist                  2.0   35000.0
154  37.0  Female        Master's               Senior Marketing Analyst                  9.0   95000.0
155  44.0    Male      Bachelor's           Senior IT Support Specialist                 14.0  110000.0
156  32.0  Female      Bachelor's               Junior Financial Analyst                  5.0   50000.0
157  33.0    Male        Master's              Senior Operations Manager                  7.0  115000.0
158  51.0  Female             PhD            Director of Human Resources                 23.0  185000.0
159  28.0    Male      Bachelor's               Junior Software Engineer                  2.0   40000.0
160  39.0  Female      Bachelor's            Senior Sales Representative                 12.0   90000.0
161  48.0    Male        Master's         Director of Product Management                 21.0  175000.0
162  30.0  Female      Bachelor's                      Junior Copywriter                  3.0   45000.0
163  35.0    Male      Bachelor's           Senior Marketing Coordinator                  7.0   80000.0
164  41.0  Female        Master's         Senior Human Resources Manager                 13.0  120000.0
165  27.0    Male      Bachelor's  Junior Business Development Associate                  1.5   35000.0
166  40.0  Female      Bachelor's                 Senior Account Manager                 14.0  110000.0
167  46.0    Male             PhD                      Senior Researcher                 18.0  150000.0
168  31.0  Female      Bachelor's                  Junior HR Coordinator                  4.0   50000.0
169  34.0    Male        Master's               Senior Software Engineer                  9.0  105000.0
170  50.0  Female        Master's                    Director of Finance                 20.0  180000.0
171  29.0    Male      Bachelor's           Junior Marketing Coordinator                  2.0   40000.0
172   NaN     NaN             NaN                                    NaN                  NaN       NaN
173  43.0    Male      Bachelor's                 Senior Project Manager                 16.0  140000.0
174  26.0  Female        Master's                  Junior Data Scientist                  1.5   45000.0
175  35.0    Male      Bachelor's              Senior Operations Analyst                  7.0   85000.0
176  42.0  Female             PhD               Senior Marketing Manager                 18.0  140000.0
177  31.0    Male      Bachelor's                      Junior Accountant                  4.0   50000.0
178  38.0  Female      Bachelor's     Senior Human Resources Coordinator                 10.0   80000.0
179  46.0    Male        Master's                 Director of Operations                 20.0  170000.0
180  29.0  Female      Bachelor's            Junior Sales Representative                  2.0   40000.0
181  37.0    Male        Master's                Senior Business Analyst                  9.0  105000.0
182  44.0  Female             PhD                     Senior UX Designer                 15.0  145000.0
183  27.0    Male      Bachelor's                 Junior Product Manager                  2.0   40000.0
184  36.0  Female      Bachelor's            Senior Marketing Specialist                  8.0   85000.0
185  43.0    Male      Bachelor's              Senior IT Project Manager                 14.0  130000.0
186  33.0  Female        Master's               Senior Financial Analyst                  6.0   95000.0
187  34.0    Male      Bachelor's       Senior Quality Assurance Analyst                  9.0  100000.0
188  50.0  Female             PhD        Director of Sales and Marketing                 22.0  180000.0
189  28.0    Male      Bachelor's              Junior Operations Analyst                  1.5   35000.0
190  39.0  Female      Bachelor's               Senior Account Executive                 12.0   95000.0

In [12]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [13]:
df.tail()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
370,35.0,Female,Bachelor's,Senior Marketing Analyst,8.0,85000.0
371,43.0,Male,Master's,Director of Operations,19.0,170000.0
372,29.0,Female,Bachelor's,Junior Project Manager,2.0,40000.0
373,34.0,Male,Bachelor's,Senior Operations Coordinator,7.0,90000.0
374,44.0,Female,PhD,Senior Business Analyst,15.0,150000.0

In [14]:
df = pd.read_csv("salary.csv", nrows=10)
df

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,Male,Bachelor's,Software Engineer,5,90000
1,28,Female,Master's,Data Analyst,3,65000
2,45,Male,PhD,Senior Manager,15,150000
3,36,Female,Bachelor's,Sales Associate,7,60000
4,52,Male,Master's,Director,20,200000
5,29,Male,Bachelor's,Marketing Analyst,2,55000
6,42,Female,Master's,Product Manager,12,120000
7,31,Male,Bachelor's,Sales Manager,4,80000
8,26,Female,Bachelor's,Marketing Coordinator,1,45000
9,38,Male,PhD,Senior Scientist,10,110000

In [15]:
df.head(2)

   Age  Gender Education Level          Job Title  Years of Experience  Salary
0   32    Male      Bachelor's  Software Engineer                    5   90000
1   28  Female        Master's       Data Analyst                    3   65000

In [16]:
df = pd.read_csv("salary.csv", nrows = 7, usecols= ["Age", "Job Title"])
df

   Age          Job Title
0   32  Software Engineer
1   28       Data Analyst
2   45     Senior Manager
3   36    Sales Associate
4   52           Director
5   29  Marketing Analyst
6   42    Product Manager